[package]
name = "cnc-control"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.14"
crossbeam = "0.8.4"
ctrlc = "3.4.7"
regex = "1.11.1"
rppal = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serialport = "4.7.2"
