logs:
  verbose: true
  save: true
  path: "~/cnc/logs/{%t}"

serial:
  port: "/dev/ttyUSB0"
  baudrate: 115200

grbl:
  rx_buffer_size_bytes: 1024

inputs:
  signal:
    pin: 17
    debounce_ms: 30
  probe_xy:
    pin: 27
    debounce_ms: 30
  probe_z:
    pin: 22
    debounce_ms: 30

steps:
  - type: gcode
    path: "~/cnc/tanks/probe.gcode"
    check: false
    points:
      save: true
      path: "~/cnc/tanks/points/tank-{%t}.csv"

  - type: bash
    wait_for_signal: false
    command: "python ~/cnc/tanks/transform.py -p ~/cnc/tanks/points/tank-{%t}.csv -o ~/cnc/tanks/cut.gcode"

  - type: gcode
    path: "~/cnc/tanks/cut.gcode"
